version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    restart: on-failure


  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on: 
      - wordpress
    restart: on-failure

volumes :
  wordpress_data :
    driver : local
    driver_opts :
      type    : 'none'
      o       : 'bind'
      device  : '/home/noe/data/wordpress'

  mariadb_data :
    driver : local
    driver_opts :
      type    : 'none'
      o       : 'bind'
      device  : '/home/noe/data/mariadb'

networks:
  inception:
    driver: bridge
