version: '3'
services:
  nginx:
    build:
      context: ./requirements/nginx
    restart: on-failure
    ports:
      - "8080:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
    networks:
      - inception

  mariadb:
    build:
      context: ./requirements/mariadb
    restart: on-failure
    expose:
      - "3306"
    env_file:
      - .env
    container_name: mariadb
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb_data:
    driver_opts:
      o : bind
      type : none
      device: /home/noe/data/db
  #   website:
  #     driver_opts:
  #       o : bind
  #       type : none
  #       device: /home/nfauconn/data/wordpress

networks:
  inception:
    driver: bridge

#version: '3'
#
#services:
#  nginx :
#    image           : nginx
#    container_name  : nginx
#    build           : requirements/nginx/
#      #    volumes :
#      #- WordPress:/var/www/wordpress
#    networks :
#      - inception
#    ports :
#      - 8080:443
#    depends_on :
#      - wordpress

#  wordpress:
#    image: wordpress:php7.4-fpm-alpine
#    environment:
#      WORDPRESS_DB_HOST: mariadb
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#    volumes:
#      - wordpress_data:/var/www/html
#    networks:
#      - inception
#    depends_on:
#      - mariadb
#
#  mariadb:
#    image: mariadb:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MDB_ROOT_PWD}
#      MYSQL_DATABASE: ${MDB_NAME}
#      MYSQL_USER: ${MDB_USR}
#      MYSQL_PASSWORD: ${MDB_USR_PWD}
#    volumes:
#      - mariadb_data:/var/lib/mysql
#    networks:
#      - inception
#
#volumes:
#  wordpress_data:
#  mariadb_data:
#
#networks:
#  inception:
#    driver: bridge
