version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure


  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "8080:443"
    networks:
      - inception
    volumes:
      - nginx_data:/etc/nginx/conf.d
    depends_on: 
      - wordpress
    restart: on-failure

volumes:
  mariadb_data:
  wordpress_data:
  nginx_data:

networks:
  inception:
    driver: bridge
