version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - wordpress

  wordpress:
    image: wordpress:php7.4-fpm-alpine
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  wordpress_data:
  mariadb_data:

networks:
  my_network:
    driver: bridge

