version: '3.5'
services:
  ngnix:
    container_name: ngnix
    build: requirements/nginx/
    restart: always
    depends_on:
      - wordpress
      - server-minecraft
      - adminer
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565"
    networks:
      - mynetwork
    volumes:
      - WordPress:/var/www/html
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    restart: always
    depends_on:
      - mariadb
    networks:
      - mynetwork
    volumes:
     - WordPress:/var/www/html
    env_file: .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    restart: always
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file: .env
  
  #BONUS 
  adminer:
    container_name: adminer
    build: requirements/adminer/
    restart: always
    networks:
      - mynetwork
    env_file: .env
  
  redis:
    container_name: redis
    build: requirements/redis/
    restart: always
    networks:
      - mynetwork
    env_file: .env
  
  static-web:
    container_name: static-web
    build: requirements/static-web/
    volumes:
     - WordPress:/var/www/html
    networks:
      - mynetwork
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  ftp:
    container_name: ftp
    build: requirements/ftp/
    restart: always
    volumes:
      - WordPress:/var/www/html
    networks:
      - mynetwork
    ports:
      - "21:21"
      - "20:20"
      - "40000-40050:40000-40050"
    env_file: .env
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  #FOR FUN
  server-minecraft:
    container_name: minecraft-server
    build: requirements/minecraft/
    restart: always
    networks:
      - mynetwork
    volumes:
      - server_minecraft_volume:/server
    restart: always


# NETWORK
networks:
  mynetwork:
    name : mynetwork
    driver : bridge

# VOLUME
volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/tliot/data/db

  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/tliot/data/wordpress

  server_minecraft_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/tliot/data/minecraft-server