#!/bin/sh
service mysql start 

# CREATE USER #
mysql -e "CREATE USER '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASSWORD';"

# PRIVILGES FOR ROOT AND USER FOR ALL IP ADRESS #
mysql -e "GRANT ALL PRIVILEGES ON *.* TO '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_USER_PASSWORD';"
mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '${SQL_ROOT_PASSWORD}';"
mysql -e "FLUSH PRIVILEGES;"

# CREAT WORDPRESS DATABASE #
mysql -e "CREATE DATABASE $MYSQL_DATABASE"

mysqladmin -u root -p$SQL_ROOT_PASSWORD shutdown

mysqld
